### ISSUE TITLE
not showing season posters in /Web edit season window

### ISSUE THREAD

**Issue by BigWheel88** [plexinc-agents/Fanart-TV.bundle#2] opened 2015-05-16 22:07 UTC
reported here https://forums.plex.tv/index.php/topic/157775-tv-shows-missing-season-posters-showing-blank-episode-posters/?p=925247

**Comment by sander1** [comment] 2015-05-17 13:33
The Movie Database (when used for TV) has the same issue. This doesn't seem to be an issue with the agents, but with /Web or the Plex framework.

**Comment by chrisallen** [comment] 2015-05-19 09:37
reported here as well https://forums.plex.tv/index.php/topic/60348-fanarttv/page-3#entry922129

**Comment by mmccurdy07** [comment] 2015-06-13 04:53
I just got a little dizzy from following this tangled web of GHI references...  but long story short: I can't reproduce this. Does anyone have clear steps to repeat (including a known-broken agent stack)?  Combinations I tried, among others:

* Fanart.tv -> TMDB -> TVDB (primary)
* Fanart.tv -> TMDB (primary) (I think there may be some other issues here, since I only got a single poster for each season in this case...)
* TMDB -> TVDB (primary) -> Fanart.tv

In every case the season posters were all visible with the primary one selected when the edit poster dialog was invoked.

**Comment by Moussa** [comment] 2015-06-13 05:02
I just set up a TV show library on my test server with an exact duplicate of the agent ordering from my affected library and the issue is present. This is what my ordering looks like

![](http://i.imgur.com/fangDP0.png)

**Comment by mmccurdy07** [comment] 2015-06-13 05:11
Hmm...  still can't repro, everything looks fine here. This happens 100% of the time for you?

**Comment by Moussa** [comment] 2015-06-13 05:13
Yea pretty much all the time, I can't recall the fanart.tv season poster thumbnails ever showing up.

**Comment by Moussa** [comment] 2015-06-13 05:16
For reference, this is one of the dead links that plex web attempts to load for the posters

`http://127.0.0.1:32400/photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2Flibrary%2Fmetadata%2F14742%2Ffile%3Furl%3Dmetadata%253A%252F%252Fseasons%252Fposters%252Fcom%252Eplexapp%252Eagents%252Efanarttv_4005e962447885d1c0f167644240d3b6bad1491e%26X-Plex-Token%3DRGJs8i6oen8VstwsGJcK&width=150&height=225&X-Plex-Token=<token>`

**Comment by mmccurdy07** [comment] 2015-06-13 05:35
Ok, got it, I had some local changes to my fanart.tv agent that was preventing it from contributing at all, so everything looked non-broken :)

**Comment by sander1** [comment] 2015-06-13 12:03
@mmccurdy07 You can also set the agents up like this (with The Movie Database and without Fanart.tv):

![screen shot 2015-06-13 at 13 53 30](https://cloud.githubusercontent.com/assets/104684/8144255/e1ac3d80-11d4-11e5-82f9-27f919e2c04f.png)

This shows the same issue:

![screen shot 2015-06-13 at 13 53 06](https://cloud.githubusercontent.com/assets/104684/8144257/f3949ea2-11d4-11e5-81d6-7396d6f3ef19.png)

**Comment by mmccurdy07** [comment] 2015-06-13 16:27
Forgot to update over here, this turned out to be a PMS issue, fixed in https://github.com/plexinc/plex-media-server/commit/22dcc00601fb75e536095f0c2e50703b07315a54.

**Closed by mmccurdy07** 2015-06-13 16:27 UTC

**Comment by sander1** [comment] 2015-06-13 17:20
@mmccurdy07 Thanks for the update!
